# Generated by Django 3.2 on 2021-04-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RZ', models.CharField(max_length=100)),
                ('zn_typ', models.CharField(max_length=100)),
                ('najeto_km', models.IntegerField(max_length=1000000)),
                ('dat_technicke', models.DateField()),
            ],
        ),
    ]
