# Generated by Django 3.2 on 2021-04-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_auto_20210419_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vypujcka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vypujceno', models.DateTimeField()),
                ('vraceno', models.DateTimeField()),
                ('cena', models.IntegerField()),
            ],
        ),
    ]
